package com.pranav.saarthi.data;


import com.pranav.saarthi.api.NotesApi;
import com.pranav.saarthi.api.RetrofitClient;
import com.pranav.saarthi.model.AiNoteResponse;
import com.pranav.saarthi.model.AiNotesListResponse;
import com.pranav.saarthi.model.Note;
import com.pranav.saarthi.model.Task;
import java.util.ArrayList;
import java.util.List;
import retrofit2.Response;

public class NetworkNotesRepository implements NotesRepository {

    private NotesApi notesApi;

    public NetworkNotesRepository() {
        notesApi = RetrofitClient.getClient().create(NotesApi.class);
    }

    @Override
    public long addNote(String text, String title, String category, String subCategory, String status, String remarks,
            String comment) {
        // ID is generated by server, passing 0. dateTime is also generated/handled by
        // server or ignored.
        // The API expects 'note' field for text, mapped via @SerializedName in Note
        // class.
        Note note = new Note(0, text, title, null, category, subCategory, status, remarks, comment);
        try {
            Response<Note> response = notesApi.addNote(note).execute();
            if (response.isSuccessful() && response.body() != null) {
                android.util.Log.d("NetworkNotesRepo", "Note saved successfully. ID: " + response.body().getId());
                return response.body().getId();
            } else {
                android.util.Log.e("NetworkNotesRepo",
                        "Failed to save note. Code: " + response.code() + ", Message: " + response.message());
                try {
                    if (response.errorBody() != null) {
                        android.util.Log.e("NetworkNotesRepo", "Error body: " + response.errorBody().string());
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            android.util.Log.e("NetworkNotesRepo", "Exception saving note", e);
            e.printStackTrace();
        }
        return -1;
    }

    @Override
    public List<Note> getAllNotes() {
        try {
            Response<List<Note>> response = notesApi.getNotes().execute();
            if (response.isSuccessful() && response.body() != null) {
                android.util.Log.d("NetworkNotesRepo", "Fetched " + response.body().size() + " notes.");
                return response.body();
            } else {
                android.util.Log.e("NetworkNotesRepo",
                        "Failed to fetch notes. Code: " + response.code() + ", Message: " + response.message());
            }
        } catch (Exception e) {
            android.util.Log.e("NetworkNotesRepo", "Exception fetching notes", e);
            e.printStackTrace();
        }
        return new ArrayList<>();
    }

    @Override
    public void deleteNote(int id) {
        try {
            Response<Void> response = notesApi.deleteNote(id).execute();
            if (response.isSuccessful()) {
                android.util.Log.d("NetworkNotesRepo", "Note deleted successfully. ID: " + id);
            } else {
                android.util.Log.e("NetworkNotesRepo",
                        "Failed to delete note. Code: " + response.code() + ", Message: " + response.message());
            }
        } catch (Exception e) {
            android.util.Log.e("NetworkNotesRepo", "Exception deleting note", e);
            e.printStackTrace();
        }
    }

    @Override
    public Note generateTitle(int noteId) {
        try {
            Response<AiNoteResponse> response = notesApi.generateTitle(noteId).execute();
            if (response.isSuccessful() && response.body() != null) {
                return response.body().getNote();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public List<Note> generateTitlesAll() {
        try {
            Response<AiNotesListResponse> response = notesApi.generateTitlesAll().execute();
            if (response.isSuccessful() && response.body() != null) {
                return response.body().getNotes();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return new ArrayList<>();
    }

    @Override
    public List<Note> generateTitlesToday() {
        try {
            Response<AiNotesListResponse> response = notesApi.generateTitlesToday().execute();
            if (response.isSuccessful() && response.body() != null) {
                return response.body().getNotes();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return new ArrayList<>();
    }

    // Task related methods
    @Override
    public long addTask(Task task) {
        try {
            Response<Task> response = notesApi.addTask(task).execute();
            if (response.isSuccessful() && response.body() != null) {
                return response.body().getId();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return -1;
    }

    @Override
    public List<Task> getAllTasks() {
        try {
            Response<List<Task>> response = notesApi.getTasks().execute();
            if (response.isSuccessful() && response.body() != null) {
                return response.body();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return new ArrayList<>();
    }

    @Override
    public void updateTask(Task task) {
        try {
            notesApi.updateTask(task.getId(), task).execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void deleteTaskFromRepo(int id) {
        try {
            notesApi.deleteTask(id).execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
